### ISSUE TITLE
Implement / automated test suite

### ISSUE THREAD

**Issue by ClaudiuCeia** [civictechro/fiipregatit.ro#16]
Basically Travis, sau orice alta solutie decenta, la alegere (ar merge si un Jenkins, doar ca trebuie sa vedem unde facem deployment pentru el)

**Comment by amsterdammer** [comment]
Mai mare daraua ca ocaua. Este atat de mult global state in Wordpress inca unit testing-ul e aproape imposibil. Ar fi entitatile noastre, dar sunt mai mult data objects (setter/getter) umplute cu wordpress stuff. 

Poate doar ceva integration tests tot in zona asta, dar o sa fie mai multa munca to set all up si apoi o sa fie slow to run, si o chestie in plus la care trebuie mentenanta. Si in final valoarea testelor va fi destul de mica.

**Comment by ClaudiuCeia** [comment]
@amsterdammer din pacate cred ca ai 100% dreptate, eram cam optimist. Inchidem for now.
