### ISSUE TITLE
Ghiduri - Focus pe "In timpul evenimentului"

### ISSUE THREAD

**Issue by mottanu** [civictechro/fiipregatit.ro#213]
#### Ce se întâmplă:
Cand intru intr-un ghid, sectiunile sunt inchise
#### Ce ar trebui să se întâmple: 
Cand intru intr-un ghid ar trebui sa fie expandata sectiunea "In timpul evenimentului", astfel incat userul sa poata citi automat un text. Sa nu fie nevoit sa mai dea inca un tap. 

#### Specificații de sistem:
Commit hash:
Sistem de operare:

**Comment by ClaudiuCeia** [comment]
cc @ionutpopacivictech 

S-a schimbat schimbarea, adica e intentionat behaviorul. In continutul primit avem foarte mult text in unele sectiuni si pe mobil nu vezi ca mai sunt si alte categorii, asa ca am decis sa le avem pe toate inchise by default si user-ul poate alege ce sectiune vrea sa deschida.

**Comment by ionutpopacivictech** [comment]
ok

**Comment by ClaudiuCeia** [comment]
Ok sa fie deschisa prima sectiune sau ok sa nu fie? :)
