### ISSUE TITLE
Config staging environment

### ISSUE THREAD

**Issue by ClaudiuCeia** [civictechro/fiipregatit.ro#41]
Cred ca ne-ar ajuta un server de staging aici. @lucianstuparu, oare putem sa facem asta pe lightsail? As vrea sa continui pe partea de implementare, poate ne poate ajuta Marius aici? Daca nu, ma ocup eu mai tarziu.

**Comment by lucianstuparu** [comment]
Am creat o masina cu Ubuntu 16.04, cu IP static 35.158.27.241.
