### ISSUE TITLE
Gaseste si repara 'broken link' 

### ISSUE THREAD

**Issue by ClaudiuCeia** [civictechro/fiipregatit.ro#460]
#### Ce se întâmplă:
Google raporteaza un broken link pe site, care duce la `despre/fiipregatit.ro` <- not a typo. Find it and kill it with fire
#### Ce ar trebui să se întâmple: 
Ar trebui sa duca la `fiipregatit.ro/despre`
#### Pași pentru reproducerea problemei:
Nu avem, din pacate, iar raportul Google nu ne spune pe ce pagina
#### Specificații de sistem:
Commit hash:
Sistem de operare:

**Comment by danmana** [comment]
Eroarea provine de pe pagina Despre:
`Un pas următor pentru DSU a fost lansarea platfomei web centralizate, disponibilă la adresa&nbsp;<a href="https://fiipregatit.ro/despre/fiipregatit.ro">fiipregatit.ro</a> ...`

Din pacate nu ma pricep la php si nu stiu unde ar trebui sa schimb.

**Comment by ClaudiuCeia** [comment]
Mulțumim frumos @danmana pentru ajutor - chiar link-ul acesta era introdus din panoul de administrare - am actualizat. 

Am observat că nu ești înscris în comunitate, dacă dorești să te implici, te așteptăm pe https://civictech.ro/hai-si-tu :)

**Comment by danmana** [comment]
Merci pentru invitatie, mi-am (re)facut contul ... Aveam cont pe vechiul govithub si canalele de slack, dar pe civictech cred ca am uitat sa imi fac
