### ISSUE TITLE
Cautarea contextuala nu returneaza cele mai bune recomandari

### ISSUE THREAD

**Issue by dsecareanu** [civictechro/fiipregatit.ro#469]
#### Ce se întâmplă:
La o cautare dupa cuvantul "cutremur" in lista de recomandari apare prima ghidul pentru incendiu.
#### Ce ar trebui să se întâmple: 
Ar trebui sa apara ghidurile pentru cutremur
#### Pași pentru reproducerea problemei:
https://fiipregatit.ro/ghiduri/
click pe casuta de search
introduce "cutremur" si verifica recomandarile afisate
#### Specificații de sistem:
Commit hash: ? :)
Sistem de operare: MacOS / Chrome

Screenshot atasat:
![image](https://user-images.githubusercontent.com/13657057/39547955-c39c0772-4e61-11e8-8f75-f9b16e61ec08.png)

**Comment by ClaudiuCeia** [comment]
Fixed :)
