### ISSUE TITLE
Inconsistenta nume campanie Jocul Rex & Andrei

### ISSUE THREAD

**Issue by dsecareanu** [civictechro/fiipregatit.ro#474]
#### Ce se întâmplă:
Numele jocului Rex & Andrei este listat in imaginea ilustrativa ca fiind Andrei & Rex (o inconsistenta de ordine a numelor).
#### Ce ar trebui să se întâmple: 
Presupunand ca imaginea este cea corecta, numele campaniei ar trebui sa fie Andrei & Rex vs. Dr Formidabilis.
#### Pași pentru reproducerea problemei:
https://fiipregatit.ro/ - sectiunea campanii
#### Specificații de sistem:
Commit hash: N/A
Sistem de operare: MacOS/Chrome

![image](https://user-images.githubusercontent.com/13657057/39562437-4f1804ac-4eb4-11e8-839a-cc138e11e990.png)

**Comment by ionutpopacivictech** [comment]
Teoretic asa e: ar trebui ca numele omului sa fie inainte, insa nu stim exact "povestea" din joc - e posibil ca Rex sa fie personajul principal.
Mai mult, sloganul jocului e:
"fiti eroi ca ei, Rex & Andrei" (sa rimeze).

Oricum, buna observatie si multumim pentru asta.
Trimit eu un mail acum catre DSU cu nelamurirea asta si vedem ce raspuns primim.
Ori schimba afisul jocului (macar imaginea online), ori ordinea numelor (de pe tricouri)...

**Comment by ionutpopacivictech** [comment]
Salut,

Am actualizat cover image pentru campania / jocul Rex & Andrei din platforma.
Am primit acordul celor de la DSU sa facem modificarile.

Multumim pentru vigilenta, a fost apreciata implicarea.
