### ISSUE TITLE
Gasit solutie pentru generat forma la genitiv a evenimentelor

### ISSUE THREAD

**Issue by ClaudiuCeia** [civictechro/fiipregatit.ro#72]
Generam titluri utilizand numele evenimentului introdus in panoul de administrare (ie: cutremur, vijelie, viscol, etc.). Problema apare in propozitii de genul: "In timpul _eveniment_". 

Solutia e:
- Fie o librarie care stie sa transforme numele evenimentului in cazul genitiv (greu)
- Fie inca un camp in panoul de administrare unde se poate introduce si cazul genitiv (silly)

Pick your poison.

**Comment by raduvoinea** [comment]
Smells like over-engineering.
De ce nu punem "In timpul evenimentului" la toate?

**Comment by ClaudiuCeia** [comment]
Merge si in timpul evenimentului daca nu apucam sa facem ceva mai ok. Ce bine era daca era pe engleza...
