### ISSUE TITLE
Avem nevoie de lista de lista de pictograme pentru ghiduri

### ISSUE THREAD

**Issue by ClaudiuCeia** [civictechro/fiipregatit.ro#93]
Pictogramele se seteaza din admin pe fiecare ghid, ar trebui sa avem o lista de pictograme reprezentative. 

@ionutpopacivictech, crezi ca poti sa ma ajuti aici? In caz ca nu e clar, ma refer la astea:

![viscol](https://user-images.githubusercontent.com/22706412/35809886-a3da032a-0a92-11e8-825c-38a8b975a51e.png)
![incendiu](https://user-images.githubusercontent.com/22706412/35809887-a3f4ea8c-0a92-11e8-903f-a0aa8ea06428.png)
![picto_cutremur](https://user-images.githubusercontent.com/22706412/35809889-a40f2960-0a92-11e8-8a84-a6a9c25ca424.png)
![prim_ajutor](https://user-images.githubusercontent.com/22706412/35809890-a429ab0a-0a92-11e8-94c7-78272f5f7407.png)

**Comment by mottanu** [comment]
stie cineva toate ghidurile ce vor fi publicate?

**Comment by ionutpopacivictech** [comment]
Da, dar azi am avut iar o intalnire cu ei si trebuie sa ne zica care sunt finale (desi acceptat mai demult 8 ghiduri) si ordinea lor la afisare.
De ex. Avalansa era (de asta vara!), au confirmat de 2 ori, acum/momentan nu mai e...
Eu am inceput si sunt in faza avansata cu pictogramele in format editabil/vector.
Sper sa le terminam cat mai repede de personalizat si sa le exportam SVG (si poate sa le facem si font icons).
Ai avea timp sa ma ajuti un pic? Adica iti dau ce am eu acum (Illustrator) si iti zic cam cum vad eu personalizarea/dar discutam si agream, bine?
Nu ma "îngiura monșer", dar trebuie pana poimaine seara sa fie gata!
Ce zici?

**Comment by mottanu** [comment]
vezi ce am adaugat eu la #214

**Comment by ionutpopacivictech** [comment]
Vineri dimineata de la 9 (pana la 16) avem user testing moderat live la sediul DSU (6 useri, 3 femei/3 barbati, 33-45 de ani, studii medii+, sa foloseasca dispozitive digitale - laptop/smartphone, sa fie parinti/casatoriti/in relatie stabila). Voi reveni cu detalii.
Pana vineri dimineata la 9 trebuie sa avem 80-85% din content pus pe site si prototipul interactiv ready to test.
Intrebare: aveti idee de un soft bun de inregistrare ecran + audio de la un laptop/microfon local si salvat local video file?
A, si sa fie si gratuit sau free trial (dar cu functionalitaile astea macar)...

**Comment by ClaudiuCeia** [comment]
Done.
